SIGINT-840-airgap
synopsys-sig/synopsys-action pull request #110
Opened 2023-06-13 05:56 UTC by kiransynopsys

2023-07-05 14:13 UTC, spurohitsynopsys commented on src/synopsys-action/tools-parameter.ts
> +    const githubAPIURL = ''
where are we setting githubAPIURL value?

2023-07-07 09:05 UTC, kishorikumar requested changes

2023-07-07 09:05 UTC, kishorikumar commented on src/synopsys-action/synopsys-bridge.ts
> +      this.bridgeExecutablePath = await tryGetExecutablePath(filePath.concat('\\synopsys-bridge'), ['.exe'])
I believe for execution, we are already setting the executable path at the time of executing. Please test it thoroughly for all the cases, if setting here does not create any issue.

2023-07-07 16:24 UTC, kiransynopsys commented on .github/workflows/blackduck.yml
> +   runs-on: [lokesh]
reverted

2023-07-07 16:24 UTC, kiransynopsys commented on .github/workflows/check-dist.yml
reverted

2023-07-07 16:25 UTC, kiransynopsys commented on .github/workflows/polaris.yml
reverted

2023-07-07 16:27 UTC, kiransynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +          info('this.getBridgeDefaultPath():'.concat(this.getBridgeDefaultPath()))
for my local testing i've added this log, will be corrected to bridge default path 
 info('bridge default path :'.concat(this.getBridgeDefaultPath()))

2023-07-07 16:55 UTC, kiransynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +        info('inputs.BRIDGE_DOWNLOAD_URL:'.concat(inputs.BRIDGE_DOWNLOAD_URL))
removed logs which were added to test the data.

2023-07-07 16:56 UTC, kiransynopsys commented on package.json
> +    "all": "npm run format && npm run lint && npm run build && npm run package",
for local testing i've removed.

2023-07-07 16:56 UTC, kiransynopsys commented on package.json
> +    "all": "npm run format && npm run lint && npm run build && npm run package",
reverted

2023-07-07 16:57 UTC, kiransynopsys commented on .github/workflows/blackduck.yml
> +          network_air_gap: true
removed

2023-07-07 16:57 UTC, kiransynopsys commented on .github/workflows/coverity.yml
> +          network_air_gap: true
reverted

2023-07-12 17:42 UTC, lsynopsys commented on src/application-constants.ts
> +export const LATEST_GLOBAL_VERSION_URL = 'https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/bridge/latest/version.txt'
do we need internal artifactory url here?

2023-07-14 09:48 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
>      this.bridgeArtifactoryURL = 'https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/'
we can add bridgeArtifactoryURL in application-constants.ts as BRIDGE_ARTIFACTORY_URL

2023-07-14 09:52 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +          info('bridge default path :'.concat(this.getBridgeDefaultPath()))
do we need these logs?

2023-07-14 09:52 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +          info('synopsys_bridge_path:'.concat(inputs.SYNOPSYS_BRIDGE_PATH))
do we need these logs?

2023-07-14 09:53 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +          info('inputs.SYNOPSYS_BRIDGE_PATH.length::'.concat(inputs.SYNOPSYS_BRIDGE_PATH))
remove unnecessary logs

2023-07-14 10:01 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +        error('Unable to locate version url')
can we make more relatable error message like: Unable to fetch the latest version from artifactory
we can check once with team.

2023-07-17 06:09 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +          if (inputs.SYNOPSYS_BRIDGE_PATH.length !== 0) {
why are we validating like inputs.SYNOPSYS_BRIDGE_PATH.length !== 0, can't we check like if(inputs.SYNOPSYS_BRIDGE_PATH.length) 
is there any specific reason to check empty string with length

2023-07-17 06:22 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +              throw new Error('bridge_default_Path '.concat(this.synopsysBridgePath, ' does not exists'))
we don't have any input variable like bridge_default_Path, can you make it **Synopsys Bridge default path does not exist**

2023-07-17 06:23 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +              throw new Error('synopsys_bridge_path '.concat(this.synopsysBridgePath, ' does not exists'))
you can use SYNOPSYS_BRIDGE_INSTALL_DIRECTORY_KEY from constants

2023-07-17 06:35 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +            if (!checkIfPathExists(this.bridgeExecutablePath)) {
where are we validating the user provided SYNOPSYS_BRIDGE_PATH, seems like you're checking the executable file path directly

2023-07-17 11:49 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +          if (inputs.SYNOPSYS_BRIDGE_INSTALL_DIRECTORY_KEY.length) {
it can be  inputs.SYNOPSYS_BRIDGE_INSTALL_DIRECTORY_KEY

2023-07-17 11:51 UTC, spurohitsynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +      //debug('Formatted command is - '.concat(formattedCommand))
we can keep this debug log

2023-07-17 12:07 UTC, kiransynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +      //debug('Formatted command is - '.concat(formattedCommand))
updated code

2023-07-17 12:32 UTC, spurohitsynopsys commented on action.yml
> +   description: 'Enable air gap'
Network Air Gap to run synopsys-action on your network
something like that u can add, let others review as well

2023-07-17 12:38 UTC, spurohitsynopsys approved these changes

2023-07-17 13:25 UTC, spurohitsynopsys commented on src/synopsys-action/download-utility.ts
> +  if (!url.includes('latest') && !validateBridgeUrl(url)) {
validate the condition

2023-07-17 14:52 UTC, lsynopsys commented on src/application-constants.ts
> +export const SYNOPSYS_BRIDGE_INSTALL_DIRECTORY_KEY = 'synopsys_bridge_install_directory'
add readme changes as well.

2023-07-17 15:54 UTC, lsynopsys commented on src/synopsys-action/input-data/blackduck.ts
> +  GITHUB_REPOSITORY_OWNER: 'GITHUB_REPOSITORY_OWNER',
This need to be defined in different file as this is not related to Blackduck

2023-07-18 07:15 UTC, lsynopsys approved these changes

2023-07-20 05:18 UTC, merged