Sigint 854 - coverity local analysis
synopsys-sig/synopsys-action pull request #113
Opened 2023-06-16 11:48 UTC by lsynopsys

2023-07-06 05:57 UTC, sig-tithi commented on action.yml
> +    description: 'Flag to run coverity locally'
msg should be consistent across all int

2023-07-12 11:08 UTC, kishorikumar requested changes

2023-07-13 05:53 UTC, spurohitsynopsys approved these changes

2023-07-13 06:02 UTC, kishorikumar approved these changes

2023-07-13 06:04 UTC, merged