refactoring code.
synopsys-sig/synopsys-action pull request #129
Opened 2023-07-22 03:13 UTC by kiransynopsys

2023-07-24 11:17 UTC, kishorikumar requested changes

2023-07-24 11:21 UTC, kiransynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +        const extractZippedFilePath: string = SYNOPSYS_BRIDGE_INSTALL_DIRECTORY_KEY || this.getBridgeDefaultPath();
we have imported inputs and respective using the SYNOPSYS_BRIDGE_INSTALL_DIRECTORY_KEY attribute 
import { BRIDGE_DOWNLOAD_URL, SYNOPSYS_BRIDGE_INSTALL_DIRECTORY_KEY } from "./inputs";

2023-07-24 11:24 UTC, kiransynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +    if (SYNOPSYS_BRIDGE_INSTALL_DIRECTORY_KEY) {
we have imported inputs and respective using the SYNOPSYS_BRIDGE_INSTALL_DIRECTORY_KEY attribute
import { BRIDGE_DOWNLOAD_URL, SYNOPSYS_BRIDGE_INSTALL_DIRECTORY_KEY } from "./inputs";

2023-07-24 11:32 UTC, kiransynopsys commented on src/synopsys-action/synopsys-bridge.ts
> +  async getSynopsysBridgeExecutablePath(): Promise<void> {
renamed function.

2023-07-24 11:38 UTC, kiransynopsys commented on src/synopsys-action/synopsys-bridge.ts
tested and validated in both the usecase.

2023-07-25 06:22 UTC, lsynopsys approved these changes

2023-07-25 06:42 UTC, spurohitsynopsys approved these changes

2023-07-25 06:43 UTC, merged