SIGINT_1414 Bridge download for ARM arch MAC
synopsys-sig/synopsys-action pull request #186
Opened 2024-01-03 07:32 UTC by sadmananik

2024-01-04 11:53 UTC, spurohitsynopsys approved these changes

2024-01-04 17:33 UTC, kishorikumar approved these changes

2024-01-04 18:06 UTC, kishorikumar requested changes

2024-01-04 18:06 UTC, kishorikumar commented on src/synopsys-action/synopsys-bridge.ts
Add corresponding test cases as well

2024-01-05 06:05 UTC, sadmananik commented on src/synopsys-action/synopsys-bridge.ts
I have added the unit tests.

2024-01-05 07:30 UTC, kishorikumar approved these changes

2024-01-23 09:06 UTC, merged